/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package autojs6-libp2p */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "edgejoin.go"

#include <stdlib.h>
#ifdef __ANDROID__
#include <android/log.h>
static void edgejoin_log_write(int prio, const char* tag, const char* text) {
	__android_log_write(prio, tag, text);
}
#else
static void edgejoin_log_write(int prio, const char* tag, const char* text) {
	(void)prio;
	(void)tag;
	(void)text;
}
#endif

// Callback invoked from Go when the local adbd (wireless-debug) endpoint is
// unreachable, so the Java/Kotlin layer can re-enable wireless debugging.
typedef void (*edge_adb_unreachable_cb)(void);
static void edgejoin_invoke_adb_unreachable(edge_adb_unreachable_cb cb) {
	if (cb != NULL) {
		cb();
	}
}

// Callback invoked from Go when resource /31025/{instance}/5 is executed.
// Returns a JSON payload string allocated by the callback owner.
typedef char* (*edge_script_execute_cb)(const char* endpoint, const char* instance_id, const char* script_text, const char* params_json);
static char* edgejoin_invoke_script_execute(edge_script_execute_cb cb, const char* endpoint, const char* instance_id, const char* script_text, const char* params_json) {
	if (cb == NULL) {
		return NULL;
	}
	return cb(endpoint, instance_id, script_text, params_json);
}

#line 1 "cgo-generated-wrapper"

#line 3 "pairing.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt32 GoInt;
typedef GoUint32 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_32_bit_pointer_matching_GoInt[sizeof(void*)==32/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* EdgeCreateIdentity(char* name);
extern char* EdgeStartClient(char* configJSON);
extern char* EdgeStopClient(void);
extern void EdgeRegisterAdbUnreachableCallback(edge_adb_unreachable_cb cb);
extern void EdgeRegisterScriptExecuteCallback(edge_script_execute_cb cb);
extern char* EdgeSetAdbProxyTarget(char* host, int port);
extern void EdgeJoinFree(char* ptr);
extern char* EdgeProvideScrcpyJar(char* data, int length);
extern char* EdgePairWireless(char* host, int port, char* code, char* packageName, char* debugHost, int debugPort);
extern char* EdgeProvisionDeviceOwner(char* debugHost, int debugPort, char* packageName);

#ifdef __cplusplus
}
#endif
